[Interface]
PrivateKey = 8OtWW5QuIveAshC8gCx/3UXvaDsOX5uwukbDzDBBREQ=
Address = 10.100.0.3/24
DNS = 10.100.0.2

[Peer]
# VPS relay
PublicKey = slbPAsHHZcj6yG6bl43asfq8bdEaCR+vjExNsTxuaFg=
Endpoint = {{VPS_SERVER_PUBLIC_IP}}:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
