[Interface]
PrivateKey = UNELZdVcbuOvMLJJS6Bcxr8Cp0vz8/xWvoj3XAT5J38=
Address = 10.100.0.1/24
ListenPort = 51820
PostUp   = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o ens3 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o ens3 -j MASQUERADE

[Peer]
# T15p
PublicKey = xuiIAKP+VXsUvmQQZARZAJ89Ve+qAnNByLId6w1zPyA=
AllowedIPs = 10.100.0.2/32

[Peer]
# MacBook
PublicKey = nv3+mzuAZPI9mcOo82Q4UZbIxNuAtoXRSJcvwEmzUhs=
AllowedIPs = 10.100.0.3/32
