[Interface]
PrivateKey = UNELZdVcbuOvMLJJS6Bcxr8Cp0vz8/xWvoj3XAT5J38=
Address = 10.100.0.1/24
ListenPort = 51820
# Forward VPN traffic and route MacBook internet to T15p (double-hop)
PostUp   = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; ip rule add from 10.100.0.3 table 100; ip route add default via 10.100.0.2 table 100
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; ip rule del from 10.100.0.3 table 100; ip route del default via 10.100.0.2 table 100

[Peer]
# T15p (0.0.0.0/0 routes MacBook internet traffic to T15p for double-hop)
PublicKey = xuiIAKP+VXsUvmQQZARZAJ89Ve+qAnNByLId6w1zPyA=
AllowedIPs = 10.100.0.2/32, 0.0.0.0/0

[Peer]
# MacBook
PublicKey = nv3+mzuAZPI9mcOo82Q4UZbIxNuAtoXRSJcvwEmzUhs=
AllowedIPs = 10.100.0.3/32
