[Interface]
PrivateKey = {{T15P_PRIVATE_KEY}}
Address = 10.100.0.2/24

[Peer]
# VPS relay
PublicKey = {{VPS_PUBLIC_KEY}}
Endpoint = {{VPS_SERVER_PUBLIC_IP}}:51820
AllowedIPs = 10.100.0.0/24
PersistentKeepalive = 25
